[base]
dimension = 9
output_dir = "output"

[solver]
name = "sim-trhepd-rheed-mb_connect"
run_scheme = "subprocess"

[solver.config]
surface_exec_file = "/home/kinoshita/tool/sim-trhepd-rheed/src/surf.exe"
bulk_output_file = "bulkP.b"
surface_template_file = "template.txt"
cal_number = [1, 2, 4, 6, 8]
#calculated_first_line =5
#calculated_last_line = 67
#row_number = 2

[solver.post]
normalization = "MS_NORM"   #"TOTAL" for Integration or "MAX" for MAX value
Rfactor_type = "A2"        #"A" for Ichimiya's or "B" for Pendry's or "A2" for squared Weight + Ichimiya's
omega = 0.5

remove_work_dir = false

[solver.param]
string_list = ["value_01", "value_02", "value_03", "value_04", "value_05", "value_06", "value_07", "value_08", "value_09"]
#degree_max = 6.5

[solver.reference]
path = "experiment.txt"
exp_number = [1, 2, 4, 6, 8]
#first =1
#last = 63

[algorithm]
name = "minsearch"
label_list = ["X1", "X2", "X3", "Y3","Z1", "Z2", "Z3", "Z4", "Z5"]

[algorithm.param]
initial_list = [0.49800, 0.98000, 1.49800, 1.49800, 5.390000, 4.790000, 3.790000, 2.090000, 1.990000]
min_list  = [0.00000, 0.50000, 1.00000, 1.00000, 4.400000, 3.800000, 2.800000, 1.100000, 1.000000]
max_list  = [1.00000, 1.50000, 2.00000, 2.00000, 6.400000, 5.800000, 4.800000, 3.100000, 3.000000]

[algorithm.minimize]
fatol = 0.01
xatol = 0.001
initial_scale_list = [ 0.0025, 0.0025, 0.0025, 0.0025, 0.01, 0.01, 0.01, 0.01, 0.01 ]
maxiter =  1000
maxfev  = 10000
