[base]
dimension = 2
output_dir = "output"

[solver]
name = "leed"
[solver.config]
path_to_solver = "./leedsatl/satl2.exe"
[solver.reference]
path_to_base_dir = "./base"

[algorithm]
name = "minsearch"
label_list = ["z1", "z2"]
[algorithm.param]
min_list = [-0.5, -0.5]
max_list = [0.5, 0.5]
initial_list = [-0.1, 0.1]
