name: Test

on: [push]

jobs:
  main:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.6, 3.9]
        python-packages: [minimum, latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: apt
        run: |
          sudo apt update
          sudo apt install openmpi-bin libopenmpi-dev

      - name: pip
        run: |
          python -m pip install -U pip
          python -m pip install --no-cache-dir -r ${GITHUB_WORKSPACE}/.github/workflows/requirements_${{ matrix.python-packages }}.txt

      - name: test
        run: |
          declare -a FAILED_TEST=()
          for testname in mapper minsearch exchange bayes transform; do
            cd ${GITHUB_WORKSPACE}/tests/${testname}
            sh ./do.sh || FAILED_TEST=(${FAILED_TEST[@]} ${testname})
          done
          if [ ${#FAILED_TEST[@]} -gt 0 ]; then
            echo "The following test(s) failed:"
            for FAILED in ${FAILED_TEST[@]}; do
              echo ${FAILED}
            done
            false
          else
            true
          fi
