name: Test

on: [push]

jobs:
  main:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.6, 3.9]
        sample: [mapper, minsearch, exchange, bayes, transform]
        python-packages: [minimum, latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: apt
        run: |
          sudo apt update
          sudo apt install openmpi-bin libopenmpi-dev

      - name: pip
        run: |
          python -m pip install -U pip
          python -m pip install -r ${GITHUB_WORKSPACE}/.github/workflows/requirements_${{ matrix.python-packages }}.txt

      - name: ${{ matrix.algorithm }}
        run: |
          cd ${GITHUB_WORKSPACE}/tests/${{ matrix.sample }}
          sh ./do.sh
